### ISSUE TITLE
Duo: Nextcloud 10+ support

### ISSUE THREAD

**Issue by jedunbar** [elie195/duo_provider#10]
Hello, Elie.

Can this be modified to work with Nextcloud 10+?

**Comment by elie195** [comment]
Hi, Nextcloud support has been brought up in the past. The issue was that the plugin required additions to the core platform (due to the requirement of displaying an iframe from duosecurity.com). I was able to submit a pull request with the required changes for ownCloud, but the Nextcloud developers didn't agree with the approach I took with ownCloud, so the plugin wasn't compatible with Nextcloud. 

I'll take a look and see if anything has changed, since it's been about a year since all of this took place. 

To go into further detail about how I addressed the issue, the ownCloud devs wanted to create a new "IProvider" class (this is the core of any 2 factor auth provider), called "IProvider2", which adds the ability to specify a custom CSP (Content Security Policy) for the Provider, and therefore allow content from duosecurity.com. The Nextcloud devs didn't like adding a new IProvider class just to add a new method, so the change wasn't ported over. 

Again, I'll take a look if anything has since changed, but if not, the best approach would probably be to propose a pull request for the Nextcloud project with the required "setCSP()" method included as part of the base IProvider class. I currently do not have the resources to create this pull request, but I may be able to in a few weeks. If you would like to create this pull request yourself, that would help. Once the ability to set a custom CSP for an IProvider is present in Nextcloud, I should be able to add Nextcloud support pretty quickly.

**Comment by jedunbar** [comment]
Hi, Elie.

Thanks for your response. Is this what you're referring to where Nextcloud wasn't keen on adding another IProvider? https://github.com/nextcloud/server/issues/1102

I also found this a long time ago, but Christoph Wurst hasn't touched it in a while: https://github.com/ChristophWurst/twofactor_duo 

When you mentioned that you "didn't have the resources to create this pull request...", what do you mean by that?

**Comment by elie195** [comment]
Correct, here is the more specific pull request that they rejected: https://github.com/nextcloud/server/pull/1124

By that, I meant that I didn't have the time required to create a pull request for Nextcloud which supports setting a custom CSP, but their way (adding the setCSP() method to the existing IProvider class), although I'm not 100% sure they would accept this pull request.

**Comment by jedunbar** [comment]
Ah, I see.

Please do let me know if you find that Nextcloud's stance has changed. In the meantime, is there no working Nextcloud Duo app, experimental or otherwise? I'd hate to think that I'm going to have to stop using Nextcloud in favor of ownCloud because Duo 2FA auth is a requirement for my environment. My production ownCloud installation is running 8.0.2, which I don't want to upgrade to 10+ just for Duo. I'd rather just move forward with my Nextcloud 12.0 server. I tried making the ownCloud Duo app work with Nextcloud, but wasn't successful. https://marketplace.owncloud.com/apps/duo

Thank you for your efforts. I hope you find that Nextcloud has changed their mind and will allow a new IProvider.

**Comment by elie195** [comment]
I'm not aware of any Duo plugins for Nextcloud. I'll go ahead and close this issue for now, since adding Nextcloud support isn't really close, and after checking, Nextcloud doesn't currently support an IProvider's ability to specify a custom CSP.
