### ISSUE TITLE
iOS application and Duo two-factor

### ISSUE THREAD

**Issue by jeffavery** [elie195/duo_provider#15]
Hello El-ad Blech,

First, thank you for this integration, I am a big Duo fan and am just trying out ownCloud. I purchased the iOS applicatoin, and it connected to my server fine. Once I enabled Duo though, Duo worked fine through the web, but the iPhone application will no longer sync. This may not be a bug, I'm not a developer, but I can assist in trouble shooting anything, if you believe it may be a bug. If this is just a case of dumb user, feel free to close this up, and I'll keep digging for solutions. Kind regards, -Jeff

info:
iPHone: 6s Plus
iOS: 10.3.3 (14G60)
iOS ownCloud App: current version from app store as of 9/3/2017
ownCloud: hosted on Dreamhost version 10.0.2 stable
error: when typing user/pass in to owncloud iPhone application the error "the user or password is incorrect" is displayed

**Comment by elie195** [comment]
Hi Jeff,

This is the expected behavior when you have a 2FA provider enabled in ownCloud. You’re not able to use your normal password in the iOS app, you’ll need to go to Settings->Personal->App Passwords and create a password there. More info: https://owncloud.org/blog/adding-two-factor-auth-to-owncloud/

I’ll go ahead and close this issue but don’t hesitate to reply if you’re still having problems.

**Comment by jeffavery** [comment]
Wow, I'm an idiot, I read that on your blog too, and didn't make the connection. Worked like a champ, thank you!

**Comment by elie195** [comment]
No problem, glad you got it working.
