### ISSUE TITLE
PHP with a version lower than 7.1 is required.

### ISSUE THREAD

**Issue by emilnd** [elie195/duo_provider#20]
Hi.
I have read that PHP-version needs to be >=5.6 for duo_provider to function.

I'm running PHP 7.2.8 on CentOS 7, and get error when I try to install duo_provider from ownCloud market: _PHP with a version lower than 7.1 is required._

How can I go about to solve this? Do I need to downgrade my php-packages or does duo_provider itself need to accept 7.2.8?

**occ -V**
ownCloud 10.0.8

**php -v**
PHP 7.2.8 (cli) (built: Jul 17 2018 09:50:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**uname -a**
Linux S181 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by elie195** [comment]
Thanks for opening this issue. In addition to a minimum PHP version of 5.6, the plugin also has a max PHP version setting, which is currently set to 7.1. [There doesn't appear to be an option to leave the "max" PHP version undefined](https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/info.html#php), so I will increase it and do some testing and hopefully release an updated version soon.

**Comment by emilnd** [comment]
That is quite interesting, I can only guess it is there to eliminate potential security threats in newly released packages.

However, I did a manual change to appinfo/info.xml -> max-version="7.1" like below
``
<dependencies>
		<owncloud min-version="10.0" max-version="10.1" />
		<php min-version="5.6" max-version="7.3" />
</dependencies>
``

After this change I managed to set up a fully working DUO-connection. Everything went very smooth.
The only thing is offcourse that ownclouds integrety-check of files is not happy :)

I don't know how frequent the release-schedule is of PHP but do you think it would be possible to give user access to a flag to override max-version?
How does other owncloud-apps work in this way?

**Comment by elie195** [comment]
Glad it's working when you manually change the max-version. It's also now working for me in my test environment with PHP 7.2 with the max-version increased.

That's an interesting solution that you're proposing, however I don't think it will work due to app signing. The files in an ownCloud app (including info.xml) need to be signed, so the signature will become invalid if modified manually, or via an app setting if it were exposed (as you've discovered).

I'm working on updating my dev environment right now, but the plan is to set the PHP max-version to 7.9, with the assumption that a minor PHP version will not introduce any breaking changes going forward. 

It seems that other ownCloud apps have also needed to increase the max-version setting to support these newer (PHP 7.2+) versions.

**Comment by elie195** [comment]
A new version (2.5.1) of the app containing the fix has been published to the marketplace, so you should get an option to update by opening the marketplace from within ownCloud.

Let me know if you're still having issues, but I suggest upgrading to this latest version, as it is signed.
