### ISSUE TITLE
Support with current ownCloud (version 10.7)

### ISSUE THREAD

**Issue by linkp** [elie195/duo_provider#25]
I notice that the Marketplace indicates that this app has only been tested to ownCloud 10.1.

FWIW, I have it running on 10.5.

I am contemplating upgrading to current which is 10.7. Do you have any idea if this app should continue working at that version?

**Comment by emilnd** [comment]
I do not have access to any owncloud environment or DUO myself anymore, so I can only propose that you should use some kind of test environment if it's mission critical. Otherwise you maybe can rely on snapshot or something similar?

I hope this helps somewhat, but as I cannot test you might need to just wait abit more for an answer :)

**Comment by linkp** [comment]
I upgraded my ownCloud instance to 10.8.0 (specifically the official ownCloud Debian package 10.8.0-1+3.1) and this duo_provider application is still working as expected.
