### ISSUE TITLE
Doesn't work in ownCloud 9.2

### ISSUE THREAD

**Issue by silentbreaksec** [elie195/duo_provider#5]
It doesn't work with 9.2. I see you recently updated it to work with ownCloud 10. Why not support 9.2 still since that's the current stable release? Or am I missing something?

**Comment by elie195** [comment]
From what I understand, version 10 is slated to be the next major release that will add the required "IProvider2" provider to the ownCloud core code. Version 9.1.4 is the current stable release as far as I can tell, which does not include "IProvider2": https://owncloud.org/install/#edition

**Comment by silentbreaksec** [comment]
I thought 2FA support was added back in ownCloud 9.1. Wasn't this plugin working before? Is there a way to get this plugin working in the current stable release?

**Comment by elie195** [comment]
2FA support was indeed added in ownCloud 9.1, but this Duo plugin won't work with the current "IProvider" class (due to requiring a custom Content Security Policy, or CSP, to display the duosecurity.com iframe). The "IProvider2" class was then added to ownCloud core, but this class isn't available in the stable release yet. It's present in the "master" branch of ownCloud core, and will be present in the next major version (if I understand correctly).

I can write a guide on how to get the plugin to work with the current stable release, but keep in mind that this sort of thing will be unsupported, since it involves modifying your existing ownCloud installation/config files, and there might be some unintended side effects. In my experience, the only side effect is a permanent warning that gets shown at the top of the page stating that the code integrity checks failed (which is expected, since the process involves adding the "IProvider2" class manually to the code, as previously mentioned).

**Comment by silentbreaksec** [comment]
That would be great! I tried modifying the minimum version of your plugin, but still get an error: "Error: this app cannot be enabled because it makes the server unstable". Any help you could provide would be appreciated. Thanks.
